# Generated by Django 4.2.29 on 2026-03-15 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, help_text='Tailwind icon class or emoji', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shops.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField()),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('pincode', models.CharField(db_index=True, max_length=10)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('contact_phone', models.CharField(max_length=15)),
                ('whatsapp_phone', models.CharField(blank=True, max_length=15)),
                ('logo', models.ImageField(blank=True, upload_to='shops/logos/')),
                ('banner', models.ImageField(blank=True, upload_to='shops/banners/')),
                ('opening_hours', models.CharField(blank=True, help_text='e.g. Mon-Sat 9AM-8PM', max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='shops.category')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
                'indexes': [models.Index(fields=['city', 'pincode'], name='shops_shop_city_5f01e1_idx'), models.Index(fields=['category'], name='shops_shop_categor_28179f_idx'), models.Index(fields=['is_verified', 'is_active'], name='shops_shop_is_veri_02ca8e_idx')],
            },
        ),
    ]
