# Generated by Django 4.2.29 on 2026-03-15 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('product_views', models.PositiveIntegerField(default=0)),
                ('whatsapp_clicks', models.PositiveIntegerField(default=0)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='shops.shop')),
            ],
            options={
                'verbose_name_plural': 'Shop Analytics',
                'ordering': ['-date'],
                'unique_together': {('shop', 'date')},
            },
        ),
    ]
